-- MySQL Script generated by MySQL Workbench
-- Tue May 28 04:45:28 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`pessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pessoa` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pessoa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(256) NOT NULL,
  `password` VARCHAR(2048) NOT NULL,
  `email` VARCHAR(256) NOT NULL,
  `avaliacao` INT NOT NULL DEFAULT 0,
  `nome` VARCHAR(256) NOT NULL,
  `NIF` INT UNSIGNED NOT NULL,
  `nr_telefone` INT UNSIGNED NULL,
  `morada` MEDIUMTEXT NOT NULL,
  `tipo` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`empresa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`empresa` ;

CREATE TABLE IF NOT EXISTS `mydb`.`empresa` (
  `pessoa_id` INT NOT NULL,
  `ramo_empresa` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`pessoa_id`),
  CONSTRAINT `fk_empresa_pessoa1`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `mydb`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`area`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`area` ;

CREATE TABLE IF NOT EXISTS `mydb`.`area` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`profissional`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`profissional` ;

CREATE TABLE IF NOT EXISTS `mydb`.`profissional` (
  `pessoa_id` INT NOT NULL,
  `preco_hora` DECIMAL(2) NOT NULL,
  `equipamento` LONGTEXT NOT NULL,
  `area_id` INT NOT NULL,
  PRIMARY KEY (`pessoa_id`),
  CONSTRAINT `fk_profissional_area1`
    FOREIGN KEY (`area_id`)
    REFERENCES `mydb`.`area` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_profissional_pessoa1`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `mydb`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_profissional_area1_idx` ON `mydb`.`profissional` (`area_id` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pedido` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pedido` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `morada` VARCHAR(256) NOT NULL,
  `descricao` MEDIUMTEXT NOT NULL,
  `dataLimite` VARCHAR(45) NOT NULL,
  `aceita_proposta` INT NOT NULL DEFAULT 0,
  `foto` VARCHAR(2048) NOT NULL,
  `pessoa_id` INT NOT NULL,
  `area_id` INT NOT NULL,
  `profissional_pessoa_id` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_pedido_pessoa1`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `mydb`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_area1`
    FOREIGN KEY (`area_id`)
    REFERENCES `mydb`.`area` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_pedido_pessoa1_idx` ON `mydb`.`pedido` (`pessoa_id` ASC);

CREATE INDEX `fk_pedido_area1_idx` ON `mydb`.`pedido` (`area_id` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`proposta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`proposta` ;

CREATE TABLE IF NOT EXISTS `mydb`.`proposta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `custo_total` INT NOT NULL,
  `homens_hora` INT NULL,
  `pedido_id` INT NOT NULL,
  `data_inicio` VARCHAR(45) NOT NULL,
  `data_fim` VARCHAR(45) NOT NULL,
  `profissional_pessoa_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_proposta_pedido1`
    FOREIGN KEY (`pedido_id`)
    REFERENCES `mydb`.`pedido` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proposta_profissional1`
    FOREIGN KEY (`profissional_pessoa_id`)
    REFERENCES `mydb`.`profissional` (`pessoa_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_proposta_pedido1_idx` ON `mydb`.`proposta` (`pedido_id` ASC);

CREATE INDEX `fk_proposta_profissional1_idx` ON `mydb`.`proposta` (`profissional_pessoa_id` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`publicidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`publicidade` ;

CREATE TABLE IF NOT EXISTS `mydb`.`publicidade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(256) NOT NULL,
  `name` VARCHAR(256) NOT NULL,
  `area_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_publicidade_area1`
    FOREIGN KEY (`area_id`)
    REFERENCES `mydb`.`area` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_publicidade_area1_idx` ON `mydb`.`publicidade` (`area_id` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`servico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`servico` ;

CREATE TABLE IF NOT EXISTS `mydb`.`servico` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pedido_id` INT NOT NULL,
  `horas` VARCHAR(45) NOT NULL DEFAULT 0,
  `equipamento` LONGTEXT NULL,
  `custo_total` INT NOT NULL DEFAULT 0,
  `avaliacao_pro` INT NOT NULL DEFAULT 0,
  `avaliacao_cli` INT NOT NULL DEFAULT 0,
  `inseriu_PDF` INT NOT NULL DEFAULT 0,
  `dir_pdf` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_servico_pedido1`
    FOREIGN KEY (`pedido_id`)
    REFERENCES `mydb`.`pedido` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_servico_pedido1_idx` ON `mydb`.`servico` (`pedido_id` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`execucao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`execucao` ;

CREATE TABLE IF NOT EXISTS `mydb`.`execucao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pessoa_id` INT NOT NULL,
  `morada` VARCHAR(256) NOT NULL,
  `descricao` VARCHAR(2048) NOT NULL,
  `foto` VARCHAR(2048) NOT NULL,
  `dataLimite` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_execucao_pessoa1`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `mydb`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_execucao_pessoa1_idx` ON `mydb`.`execucao` (`pessoa_id` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`area_subcontratacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`area_subcontratacao` ;

CREATE TABLE IF NOT EXISTS `mydb`.`area_subcontratacao` (
  `execucao_id` INT NOT NULL,
  `area_id` INT NOT NULL,
  PRIMARY KEY (`execucao_id`, `area_id`),
  CONSTRAINT `fk_execucao_has_area_execucao1`
    FOREIGN KEY (`execucao_id`)
    REFERENCES `mydb`.`execucao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_execucao_has_area_area1`
    FOREIGN KEY (`area_id`)
    REFERENCES `mydb`.`area` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_execucao_has_area_area1_idx` ON `mydb`.`area_subcontratacao` (`area_id` ASC);

CREATE INDEX `fk_execucao_has_area_execucao1_idx` ON `mydb`.`area_subcontratacao` (`execucao_id` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`subcontratacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`subcontratacao` ;

CREATE TABLE IF NOT EXISTS `mydb`.`subcontratacao` (
  `profissional_pessoa_id` INT NOT NULL,
  `execucao_id` INT NOT NULL,
  PRIMARY KEY (`profissional_pessoa_id`, `execucao_id`),
  CONSTRAINT `fk_profissional_has_execucao_profissional1`
    FOREIGN KEY (`profissional_pessoa_id`)
    REFERENCES `mydb`.`profissional` (`pessoa_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_profissional_has_execucao_execucao1`
    FOREIGN KEY (`execucao_id`)
    REFERENCES `mydb`.`execucao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_profissional_has_execucao_execucao1_idx` ON `mydb`.`subcontratacao` (`execucao_id` ASC);

CREATE INDEX `fk_profissional_has_execucao_profissional1_idx` ON `mydb`.`subcontratacao` (`profissional_pessoa_id` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`reclamacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`reclamacao` ;

CREATE TABLE IF NOT EXISTS `mydb`.`reclamacao` (
  `pedido_id` INT NOT NULL,
  `pessoa_id` INT NOT NULL,
  `reclamacao` MEDIUMTEXT NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_reclamacao_pedido1`
    FOREIGN KEY (`pedido_id`)
    REFERENCES `mydb`.`pedido` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_reclamacao_pedido1_idx` ON `mydb`.`reclamacao` (`pedido_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
